language: c
compiler: gcc

env:
  - DEBUG=""
  - DEBUG="--enable-debug"

script:
  - git rev-parse --git-dir >/dev/null
  - git log -1 --format=format:%ci%n | sed -e 's/ [-+].*$//;s/ /T/;s/^/D /' > manifest
  - echo $(git log -1 --format=format:%H) > manifest.uuid
  - ./configure --enable-load-extension --enable-json1 --enable-fts4 --enable-fts5 --enable-replication ${DEBUG}
  - make
  - make testfixture
  - ./testfixture ./test/replication.test
  - make amalgamation-tarball
  - tar cfz build-amd64.tar.gz --transform 's|.libs/||g' sqlite3.h .libs/libsqlite3.so*
  - mkdir deploy
  - mv build-amd64.tar.gz deploy/sqlite-amd64${DEBUG}-$(cat VERSION).tar.gz
  - \[ -n "$DEBUG" \] || mv sqlite-autoconf-*.tar.gz deploy/sqlite-src-$(cat VERSION).tar.gz

deploy:
  provider: releases
  api_key: '$GITHUB_API_KEY'
  file_glob: true
  file: 'deploy/*'
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
